name: ci

on:
  pull_request:
  push:
    branches:
      - new

jobs:
  publish:
     runs-on: ubuntu-latest 
     steps:
            - uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login do docker hub
              env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
              run: |
                docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            - name: build-push-image                  
              id: docker_build 
              uses: docker/build-push-action@v2
              with:
                context: ./docker/puppetdb
                file: ./docker/puppetdb/Dockerfile
                platforms: linux/amd64,linux/arm64
                tags: abhay900/puppetserver:latest
